# Generated by Django 4.0.7 on 2022-08-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('address1', models.CharField(max_length=64, null=True)),
                ('address2', models.CharField(max_length=64, null=True)),
                ('city', models.CharField(max_length=32, null=True)),
                ('county', models.CharField(max_length=32, null=True)),
                ('state', models.CharField(max_length=32, null=True)),
                ('zipcode', models.CharField(max_length=5, null=True)),
                ('phone', models.PositiveBigIntegerField(null=True)),
            ],
        ),
    ]
